# Generated by Django 4.2.1 on 2023-05-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_photos_delete_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='img',
            new_name='image',
        ),
    ]
