# Generated by Django 4.2.1 on 2023-05-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_rename_img_photos_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
