# Generated by Django 4.2.1 on 2023-06-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
